develop:
  extends:
    file: base.yml
    service: base
  env_file:
    - dev.env
  command: develop
  links:
    - mongo
    - redis
  restart: always
  volumes:
    - ./app:/opt/control-tower/app
    - /var/run/docker.sock:/var/run/docker.sock 

# varnish:
#   extends:
#     file: base.yml
#     service: varnish
#   links:
#     - develop
#   volumes:
#     - ./varnish/default.vcl:/etc/varnish/default.vcl

mongo:
  extends:
    file: base.yml
    service: mongo
redis:
  extends:
    file: base.yml
    service: redis
